// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQOk4TCFtIkYd_tnY1mLAQp0WMdtCd594',
    appId: '1:730375018040:web:a42a72aa047d421f94f8cd',
    messagingSenderId: '730375018040',
    projectId: 'asroostore-74b24',
    authDomain: 'asroostore-74b24.firebaseapp.com',
    storageBucket: 'asroostore-74b24.appspot.com',
    measurementId: 'G-HLQ652E9EG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-ybo6Bbv-Zr_YhCn_fDGAsK5RplPJ_TI',
    appId: '1:730375018040:android:b008c77a0be3dab294f8cd',
    messagingSenderId: '730375018040',
    projectId: 'asroostore-74b24',
    storageBucket: 'asroostore-74b24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAedCWoTYw6DuKeQ2Q-POTfvr4gvN9yoE4',
    appId: '1:730375018040:ios:c0e3e918a93d061794f8cd',
    messagingSenderId: '730375018040',
    projectId: 'asroostore-74b24',
    storageBucket: 'asroostore-74b24.appspot.com',
    iosBundleId: 'com.example.asroStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAedCWoTYw6DuKeQ2Q-POTfvr4gvN9yoE4',
    appId: '1:730375018040:ios:c0e3e918a93d061794f8cd',
    messagingSenderId: '730375018040',
    projectId: 'asroostore-74b24',
    storageBucket: 'asroostore-74b24.appspot.com',
    iosBundleId: 'com.example.asroStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQOk4TCFtIkYd_tnY1mLAQp0WMdtCd594',
    appId: '1:730375018040:web:586ffb736a07736a94f8cd',
    messagingSenderId: '730375018040',
    projectId: 'asroostore-74b24',
    authDomain: 'asroostore-74b24.firebaseapp.com',
    storageBucket: 'asroostore-74b24.appspot.com',
    measurementId: 'G-Y9YQWFMHQ1',
  );
}
